---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8088}]
    - ["forwarded_port", {guest: 443, host: 5443}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[request_tracker::default]
    attributes:
